name: 7.1 Pipeline
on: 
  workflow_dispatch:


env:
 # verbosity setting for Terraform logs
 TF_LOG: WARN
 # S3 bucket for the Terraform state
 BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
 OWNER: ${{ vars.OWNER }}
 FIXED_IMAGE_TAG: ${{ vars.FIXED_IMAGE_TAG }}

permissions:
  id-token: write
  contents: write

jobs:
  exercise-7-1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./exercises/7-troubleshooting/deploy

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
